insert into employee (id, name, job, salary) values (1, 'Hunter Jasik', 'Assistant Manager', 3043.21);
insert into employee (id, name, job, salary) values (2, 'Brandise Gleeson', 'Biostatistician II', 2695.96);
insert into employee (id, name, job, salary) values (3, 'Lyssa Bax', 'VP Product Management', 4998.12);
insert into employee (id, name, job, salary) values (4, 'Malvin Valti', 'Dental Hygienist', 2835.48);
insert into employee (id, name, job, salary) values (5, 'Cass Freeborne', 'Systems Administrator III', 2183.67);
insert into employee (id, name, job, salary) values (6, 'Maddie Losty', 'Pharmacist', 4395.61);
insert into employee (id, name, job, salary) values (7, 'Franzen Purshouse', 'Nurse Practicioner', 3959.69);
insert into employee (id, name, job, salary) values (8, 'Lockwood Tarbath', 'Accountant I', 3651.62);
insert into employee (id, name, job, salary) values (9, 'Polly Bittlestone', 'Accountant I', 1876.92);
insert into employee (id, name, job, salary) values (10, 'Augustine Sambrok', 'Dental Hygienist', 1339.26);
insert into employee (id, name, job, salary) values (11, 'Bruno Andriveaux', 'Recruiter', 2848.13);
insert into employee (id, name, job, salary) values (12, 'Ambur Krale', 'Structural Engineer', 4891.67);
insert into employee (id, name, job, salary) values (13, 'Maryl Tassaker', 'VP Product Management', 1787.44);
insert into employee (id, name, job, salary) values (14, 'Sylvia Whiteford', 'Assistant Manager', 1330.99);
insert into employee (id, name, job, salary) values (15, 'Theo Finley', 'Electrical Engineer', 1730.64);
insert into employee (id, name, job, salary) values (16, 'Vince Hentze', 'Graphic Designer', 4952.8);
insert into employee (id, name, job, salary) values (17, 'Ravi Heavyside', 'Nuclear Power Engineer', 1027.51);
insert into employee (id, name, job, salary) values (18, 'Aloisia Sorrel', 'Social Worker', 1756.8);
insert into employee (id, name, job, salary) values (19, 'Ephrem Summerson', 'Assistant Professor', 1157.96);
insert into employee (id, name, job, salary) values (20, 'Corbie Marsland', 'Environmental Tech', 2673.58);
insert into employee (id, name, job, salary) values (21, 'Peyton Abberley', 'VP Accounting', 4540.39);
insert into employee (id, name, job, salary) values (22, 'Siusan Trounce', 'Speech Pathologist', 1479.28);
insert into employee (id, name, job, salary) values (23, 'Selia Olley', 'Clinical Specialist', 2372.63);
insert into employee (id, name, job, salary) values (24, 'Dolley Weighell', 'Dental Hygienist', 1192.86);
insert into employee (id, name, job, salary) values (25, 'Alyosha Daniele', 'Nurse', 4051.48);
insert into employee (id, name, job, salary) values (26, 'Ewan Cordell', 'Accountant II', 1061.92);
insert into employee (id, name, job, salary) values (27, 'Werner Lovelady', 'Nurse', 4957.7);
insert into employee (id, name, job, salary) values (28, 'Alida Reiners', 'Account Executive', 1414.09);
insert into employee (id, name, job, salary) values (29, 'Marti Haugen', 'Software Consultant', 1462.27);
insert into employee (id, name, job, salary) values (30, 'Kriste McKeney', 'GIS Technical Architect', 3873.78);
insert into employee (id, name, job, salary) values (31, 'Doroteya Zanuciolii', 'Media Manager I', 1992.17);
insert into employee (id, name, job, salary) values (32, 'Georgianna Henniger', 'Electrical Engineer', 3240.02);
insert into employee (id, name, job, salary) values (33, 'Betsy McDoual', 'Project Manager', 2796.84);
insert into employee (id, name, job, salary) values (34, 'Delila Cowlam', 'Mechanical Systems Engineer', 4167.86);
insert into employee (id, name, job, salary) values (35, 'Rancell Franiak', 'Software Engineer II', 4954.48);
insert into employee (id, name, job, salary) values (36, 'Tabitha Wadesworth', 'Tax Accountant', 1124.24);
insert into employee (id, name, job, salary) values (37, 'Ezra Macias', 'VP Quality Control', 4325.88);
insert into employee (id, name, job, salary) values (38, 'Giffard McGlashan', 'Internal Auditor', 4645.52);
insert into employee (id, name, job, salary) values (39, 'Amalee Kerfut', 'Software Test Engineer I', 2745.44);
insert into employee (id, name, job, salary) values (40, 'Susy Bowkley', 'Pharmacist', 3811.81);
insert into employee (id, name, job, salary) values (41, 'Robb Sainsbury', 'Dental Hygienist', 2920.42);
insert into employee (id, name, job, salary) values (42, 'Lowell Diben', 'Nurse Practicioner', 1255.04);
insert into employee (id, name, job, salary) values (43, 'Petunia Kenwin', 'Accounting Assistant I', 3857.21);
insert into employee (id, name, job, salary) values (44, 'Emmalee Tatlow', 'Junior Executive', 1453.74);
insert into employee (id, name, job, salary) values (45, 'Nettle Payn', 'Research Nurse', 3078.52);
insert into employee (id, name, job, salary) values (46, 'Moss Ganders', 'Structural Engineer', 3779.12);
insert into employee (id, name, job, salary) values (47, 'Reinaldo Vinnicombe', 'Marketing Assistant', 3044.29);
insert into employee (id, name, job, salary) values (48, 'Barclay Graveson', 'Pharmacist', 4259.16);
insert into employee (id, name, job, salary) values (49, 'Windham McDonell', 'Account Coordinator', 2375.5);
insert into employee (id, name, job, salary) values (50, 'Jarad Boswood', 'Operator', 1009.69);
